CREATE TABLE `all_alphas` (
  `id` int(11) NOT NULL,
  `region` varchar(3) DEFAULT NULL,
  `universe` varchar(32) DEFAULT NULL,
  `delay` tinyint(4) DEFAULT NULL,
  `alpha` varchar(512) DEFAULT NULL,
  `decay` tinyint(4) DEFAULT NULL,
  `neutralization` varchar(32) DEFAULT NULL,
  `phase` tinyint(4) DEFAULT NULL,
  `simulated` tinyint(4) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `simulate_id` varchar(32) DEFAULT NULL,
  `sharp` float DEFAULT NULL,
  `fitness` float DEFAULT NULL,
  `passed` tinyint(4) DEFAULT NULL,
  `used` tinyint(4) DEFAULT NULL,
  `alpha_id` varchar(32) DEFAULT NULL,
  `category` varchar(32) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `turnover` float DEFAULT NULL,
  `dataset` varchar(32) DEFAULT NULL,
  `fail_reasons` json DEFAULT NULL,
  `submitted` tinyint(1) DEFAULT '0',
  `template` varchar(32) DEFAULT NULL,
  `is_long` smallint(6) DEFAULT NULL,
  `is_short` smallint(6) DEFAULT NULL,
  `train_long` smallint(6) DEFAULT NULL,
  `train_short` smallint(6) DEFAULT NULL,
  `test_long` smallint(6) DEFAULT NULL,
  `test_short` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique_fields` (`region`, `delay`, `universe`, `neutralization`, `decay`, `alpha`)
)

CREATE TABLE `dataset_used` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `region` varchar(3) DEFAULT NULL,
  `universe` varchar(32) DEFAULT NULL,
  `delay` int(11) DEFAULT NULL,
  `dataset` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `template` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique_fields` (`region`, `universe`, `delay`, `dataset`, `template`)
)